### ISSUE TITLE
Coming soon page

### ISSUE THREAD

**Issue by anhnt** [anhnt/paspaley#1]
Webpage
- Can we please unbold the “Subscribe” button? It doesn’t seem to be matching the style in the PSDs

Registration pop-up
- As per PSDs please change copy to read "Be the first to view our stunning short film by Ariel Kleiman.”
- As per PSDs please make the check box yellow
- For the check box, please change the date of "September 28" to read "October 1"
- When I register and I un-tick the competition checkbox and hit submit, it accepts my entry. But when I register again using the exact same details and I decide to tick the competition checkbox, will Kademi save my details as entering into the competition even though it detects that I have already registered? There may be instances where people sign up and forget to tick the box first time round, so they decide to fill out the form again to enter the competition. How do we handle what segment groups these people will fall under in Kademi?

Terms & Conditions page
- Replace entire copy with the following instead:

Behind the Lens – Film Premiere

To launch our latest collection, we’ve returned to our pearling origins, the pristine waters of The Kimberley; with acclaimed film director Ariel Kleiman, fashion photographer Regan Cameron and international actress Clara Paget. The result, a short film capturing the beauty of Maxima set in a location truly unique to our heritage.

We are hosting an exclusive premiere of ‘Behind the Lens’ with director Ariel Kleiman in Sydney on 1st October 2015.

For your chance to attend, please submit your details below.

Recipients will be notified via email on Tuesday September 29.

Terms and Conditions
NSW Permit Number LTPS/15/06653

Each winner will receive two (2) tickets to the screening at the Golden Age Cinema and Bar in Sydney on October 1 2015. Winners will be selected at random and notified via telephone and email by 5pm AEST on Tuesday September 29. The prize is limited to tickets to the premiere only, and excludes flights, accommodation or any other inclusions. Tickets are not redeemable for cash and are non-transferrable.

Mobile Version 
- In hamburger nav when I click on Boutique Locator it takes me to a black screen - it needs to take the user to http://www.paspaley.com/boutique-locator

**Comment by anhnt** [comment]
@lettiem I've upadated all items except the following:

> When I register and I un-tick the competition checkbox and hit submit, it accepts my entry. But when I register again using the exact same details and I decide to tick the competition checkbox, will Kademi save my details as entering into the competition even though it detects that I have already registered? There may be instances where people sign up and forget to tick the box first time round, so they decide to fill out the form again to enter the competition. How do we handle what segment groups these people will fall under in Kademi?

Can you please confirm when users tick to checkbox and hit submit, they will be added to Competion group as well as Coming Soon group? 
If yes, so when users want to tick the checkbox and submit again, firstly they will be checked if already registered, then they will be added to the Competition group.

**Comment by anhnt** [comment]
I suggest this checkbox should be checked by default because we cant check if user has already ticked this check or not so (kademi doesnt support this feature at the moment). The flow should be: User enters info, the checkbox should be ticked by default, then when user submits form, they will be added into main group (_Registration 2015_) as well as two other groups: _Coming-Soon_ and _Premiere-Launch-Competition_
@lettiem Please let me know your thoughts?

**Comment by lettiem** [comment]
This sounds like a good workflow.

Please make the checkbox ticked on default but make also this checkbox an optional field.

I am out of the office for the next few days. Could you please Cc Nathan Dawes in all emails?

Many thanks
Lettie

On 5 Sep 2015, at 12:06 pm, Anh Nguyen notifications@github.com wrote:

I suggest this checkbox should be checked by default because we cant check if user has already ticked this check or not so (kademi doesnt support this feature at the moment). The flow should be: User enters info, the checkbox should be ticked by default, then when user submits form, they will be added into main group (Registration 2015) as well as two other groups: Coming-Soon" and *Premiere-Launch-Competition
@lettiem Please let me know your thoughts?

**Comment by lettiem** [comment]
@anhnt In the Thank You pop-ups could you please make the "Back to Site" buttons align more to the left so that it is not so close to the arrow? It needs match the PSDs.

**Comment by anhnt** [comment]
@lettiem It will look like this (without "Behind the lens" text :-) ![popup](https://cloud.githubusercontent.com/assets/735555/9699119/fde6f644-53ff-11e5-9cde-308cfab04e97.PNG)

FYI - I have already cc to Nathan in all email. Thanks

**Comment by lettiem** [comment]
@anhnt I see it now, had to clear my cache again. It looks good, thanks

**Comment by lettiem** [comment]
@anhnt the above changes seem to look ok. We just need to test the EDMs again. Let us know when you have deleted the data so that we can register again.

**Comment by anhnt** [comment]
@lettiem please register again. I have removed all of your records

**Comment by lettiem** [comment]
On iPhone in landscape mode when I submit the rego form for the first time "Thank You" pop-up shows both Thank You messages, see screenshot attached. When I rotate to portrait mode both Thank You messages still appear. It is working find on iPad mini and my Mac Laptop
![img_1674](https://cloud.githubusercontent.com/assets/9561347/9701883/fc2b0396-5485-11e5-9811-3ccdfcf3a0a9.jpg)

**Comment by anhnt** [comment]
Hi @lettiem, I think it's cache issue. Can you please clear your iPhone browser cache and try again?

**Comment by lettiem** [comment]
Hi Anh,

For the coming soon page please make sure that registrations only fall in these respective groups - Coming-Soon and Premiere-Launch-Competition

When we go live with the rest of the site registrations then need to fall under these respective groups - Existing Clients, 2014 Registrations, 2015 Registrations and Premiere-Launch-Competition

Thanks
Lettie

On 5 Sep 2015, at 12:06 pm, Anh Nguyen notifications@github.com wrote:

I suggest this checkbox should be checked by default because we cant check if user has already ticked this check or not so (kademi doesnt support this feature at the moment). The flow should be: User enters info, the checkbox should be ticked by default, then when user submits form, they will be added into main group (Registration 2015) as well as two other groups: Coming-Soon" and *Premiere-Launch-Competition
@lettiem Please let me know your thoughts?

**Comment by anhnt** [comment]
Hi @lettiem ,

Currently user will be added to main group named 2015 Registrations and opt-in to 2 other groups: Coming-Soon and Premiere-Launch-Competition. The old database I've imported to 2014-Registrations. Since kademi allows users to be in many groups so I decided to add them as above.

if it's not correct or needs to tweak something please let me know. And can you please explain more details about each group above? I'm little bit confused what do they mean?

Many thanks
